# Generated by Django 6.0.3 on 2026-05-11 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in listing', max_length=500)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('category', models.CharField(choices=[('fever', 'Fever & Temperature'), ('pain', 'Pain Relief'), ('cough', 'Cough & Cold'), ('diabetes', 'Diabetes Care'), ('bloodpressure', 'Blood Pressure'), ('heartdisease', 'Heart Disease'), ('vitamins', 'Vitamins & Supplements'), ('allergy', 'Allergy'), ('asthma', 'Asthma'), ('digestivehealth', 'Digestive Health'), ('skin', 'Skin Care'), ('mentalhealth', 'Mental Health'), ('nutrition', 'Nutrition & Diet'), ('fitness', 'Fitness & Exercise'), ('firstaid', 'First Aid'), ('general', 'General Health')], default='general', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
