# Generated by Django 6.0.3 on 2026-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
