# Generated by Django 6.0.3 on 2026-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='General Inquiry', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
